### ISSUE TITLE
Local builds in docker as system user (not root) not running

### ISSUE THREAD

**Issue by ok-mo** [swedishembedded/sdk#20]
Since a docker image for the latest develop docker image is [not currently available](https://github.com/swedishembedded/develop/actions/runs/3488662367/jobs/5837763534), I did my own [docker build](https://github.com/ok-mo/se-sdk-develop/actions/runs/3505744360/jobs/5873480093) from a [fork of latest develop](https://github.com/ok-mo/se-sdk-develop). I then was able to get a successful build of a fork of this sdk using this l[atest docker](https://github.com/ok-mo/sdk/actions/runs/3506838099/workflow#L20) (image posted to [docker hub](https://hub.docker.com/r/okmo/develop/tags)).

For some reason, when I try to run the same sdk build sequence (from ci.yml) locally, using my own develop docker image, it does not build. I am getting:
```
SDK /build/platform/sdk > ./scripts/build
Zephyr (/build/platform/zephyr/share/zephyr-package/cmake)
has been added to the user package registry in:
~/.cmake/packages/Zephyr

ZephyrUnittest (/build/platform/zephyr/share/zephyrunittest-package/cmake)
has been added to the user package registry in:
~/.cmake/packages/ZephyrUnittest

INFO    - Zephyr version: zephyr-v2.4.0-20407-gf8f665797343
INFO    - JOBS: 4
ERROR   - Cmake script failure: /build/platform/zephyr/cmake/modules/verify-toolchain.cmake
E: CMake Error at /build/platform/zephyr/cmake/modules/verify-toolchain.cmake:84 (find_package):
  Could not find a package configuration file provided by "Zephyr-sdk"
  (requested version 0.13.1) with any of the following names:

    Zephyr-sdkConfig.cmake
    zephyr-sdk-config.cmake

  Add the installation prefix of "Zephyr-sdk" to CMAKE_PREFIX_PATH or set
  "Zephyr-sdk_DIR" to a directory containing one of the above files.  If
  "Zephyr-sdk" provides a separate development package or SDK, be sure it has
  been installed.



Error while trying to build project
SDK /build/platform/sdk > 
```
I get the same result from running (it can't find the board?):
```
SDK /build/platform/sdk > west build -b custom_board -d build-apps/custom_board/shell/apps.shell.release/ -s apps/shell -p
-- west build: generating a build system
Loading Zephyr default modules (Zephyr base).
-- Application: /build/platform/sdk/apps/shell
-- Found Python3: /usr/bin/python3.8 (found suitable exact version "3.8.10") found components: Interpreter
-- Cache files will be written to: /home/user/.cache/zephyr
-- Zephyr version: 3.1.0 (/build/platform/zephyr)
-- Found west (found suitable version "0.14.0", minimum required is "0.7.1")
CMake Warning at /build/platform/zephyr/cmake/modules/boards.cmake:85 (message):
  BOARD_ROOT element without a 'boards' subdirectory:

  /build/platform/modules/test/testing

  Hints:

    - if your board directory is '/foo/bar/boards/<ARCH>/my_board' then add '/foo/bar' to BOARD_ROOT, not the entire board directory
    - if in doubt, use absolute paths
Call Stack (most recent call first):
  /build/platform/zephyr/cmake/modules/zephyr_default.cmake:121 (include)
  /build/platform/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:51 (include)
  /build/platform/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:76 (include_boilerplate)
  CMakeLists.txt:7 (find_package)


-- Board: custom_board
CMake Error at /build/platform/zephyr/cmake/modules/verify-toolchain.cmake:84 (find_package):
  Could not find a package configuration file provided by "Zephyr-sdk"
  (requested version 0.13.1) with any of the following names:

    Zephyr-sdkConfig.cmake
    zephyr-sdk-config.cmake

  Add the installation prefix of "Zephyr-sdk" to CMAKE_PREFIX_PATH or set
  "Zephyr-sdk_DIR" to a directory containing one of the above files.  If
  "Zephyr-sdk" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  /build/platform/zephyr/cmake/modules/zephyr_default.cmake:121 (include)
  /build/platform/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:51 (include)
  /build/platform/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:76 (include_boilerplate)
  CMakeLists.txt:7 (find_package)


-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake -DWEST_PYTHON=/usr/bin/python3 -B/build/platform/sdk/build-apps/custom_board/shell/apps.shell.release -S/build/platform/sdk/apps/shell -GNinja -DBOARD=custom_board
SDK /build/platform/sdk >
```
This seems to be a common zephyr app build problem, but have not yet found a fix. Any suggestions?

If you can build your own latest develop docker image (or use mine), you should be able to reproduce the problem locally?

**Comment by mkschreder** [comment]
Are you still facing this even with latest docker image? https://github.com/swedishembedded/develop

I haven't seen this for a while but basically it is caused by the zephyr toolchain (zephyr sdk) not being initialized for the user under whom the command is being run (the zephyr toolchain setup.sh script sets this up but only for root and since you are running as user in your image it also should have been executed for the user so that cmake environment is saved for the unprivileged user as well). 

I remember fixing it before by simply executing "setup.sh" command for zephyr sdk for the system user under which I then plan to run the build process inside docker (usually "user"). So you can either run as root inside docker or make sure zephyr sdk environment has been setup within the container for the unprivileged user as well.

**Comment by ok-mo** [comment]
As mentioned above, since you had a problem with the build of https://github.com/swedishembedded/develop, I fixed the build problem in a fork (be editing CI.yml -  and temporarily publishing my own image). I am using this image as the 'latest' version of 'develop'. 

Using the following I was able to run the CI sequence of commands in my temporary 'develop' docker container.
```
sudo su - root
cd /build/platform/sdk/
git config --global --add safe.directory '*'
./scripts/init
/opt/toolchains/zephyr-sdk-0.15.1/setup.sh -t all -h -c
./scripts/gen-tags cscope
./scripts/check
./scripts/build
./scripts/test
robot post-build
```
The board build also now works
```
west build -b custom_board -d build-apps/custom_board/shell/apps.shell.release/ -s apps/shell -p
```

So it seems to boil down to setting privileges for 'user' in the docker container. I tried to find a 'setup.sh' type script but so far no luck. I will continue looking.

In the meantime, any suggestions for setting 'user' privileges for running in a zephyr container (such as your 'develop' container)? It's probably one of those things where it is obvious when you know how. So far I have not found it.

**Comment by ok-mo** [comment]
Ah, looks like I found the problem. 

I tried running https://github.com/zephyrproject-rtos/example-application in 'develop' container. At first it did not work, then I noticed the CI build was using [CMAKE_PREFIX_PATH: /opt/toolchains](https://github.com/zephyrproject-rtos/example-application/blob/main/.github/workflows/build.yml#L10). After I set this the example-application build succeeded. 

Translating this to the SDK sample app, the following resulted in a successful build:
```
docker run -ti --name se-sdk-1 okmo/develop:main
cd /build/platform/sdk/
export CMAKE_PREFIX_PATH=/opt/toolchains
west build -b custom_board -d build-apps/custom_board/shell/apps.shell.release/ -s apps/shell -p
```

For your latest image replace `okmo/develop:main` with `swedishembedded/develop:main` (or whatever tag is available in https://hub.docker.com/r/swedishembedded/develop/tags)

I recommend adding CMAKE_PREFIX_PATH=/opt/toolchains to https://github.com/swedishembedded/develop/blob/main/Dockerfile.develop 
to get a build-ready container from image.
