### ISSUE TITLE
Excessive clang-tidy lint errors?

### ISSUE THREAD

**Issue by ok-mo** [swedishembedded/sdk#22]
After installing clang-tidy-10, lint errors are exceeding allowable log length in build ([logs_8.zip](https://github.com/swedishembedded/sdk/files/10074240/logs_8.zip)).

Is this a good or a bad thing?

**Comment by mkschreder** [comment]
Generated files should not be linted. Why is your build ending up under apps?

**Comment by mkschreder** [comment]
I believe this one is solved now.
